### ISSUE TITLE
Can we discuss the ownership of this package name?

### ISSUE THREAD

**Issue by termosa** [jamesplease/use-request#1]
Hello @jamesplease!

I have a good solution for the library that you planned to put under this name.
I'd be happy to discuss it with you if you are open to such a conversation.

Please, answer this thread or email me at termosa.stanislav@gmail.com.
Thanks in advance!

**Comment by jamesplease** [comment]
Hey @termosa , thanks for opening the issue. If you drop your npm email here I'll transfer ownership of the package to you.

**Comment by termosa** [comment]
Much appreciated James!

The email is the same: termosa.stanislav@gmail.com
Will publish that soon and will leave a thanks note at your address!

**Comment by jamesplease** [comment]
No thanks is necessary! Also, it looks like I'll need your npm username rather than the email. Sorry about that. If you drop your npm username here I'll add you ASAP!

**Comment by termosa** [comment]
it is the same thing everywhere `@termosa`

**Comment by jamesplease** [comment]
OK, invite sent! Go ahead and remove me as a collaborator to take full control of the package. And don't worry about giving me any attribution/thanks/etc ✌️

**Comment by termosa** [comment]
@jamesplease thanks a lot!
